<a href="https://colab.research.google.com/github/MFahim-Data/Full-Stack-Data-Analytics/blob/main/Student_Data_Analysis_Day_4_Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files
upload = files.upload()

Saving GDP (nominal) per Capita.csv to GDP (nominal) per Capita.csv

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("GDP (nominal) per Capita.csv")

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
df.head(10)

,Unnamed: 0,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
0,1,Monaco,Europe,0,0,234316,2021,234317,2021
1,2,Liechtenstein,Europe,0,0,157755,2020,169260,2021
2,3,Luxembourg,Europe,132372,2023,133590,2021,133745,2021
3,4,Ireland,Europe,114581,2023,100172,2021,101109,2021
4,5,Bermuda,Americas,0,0,114090,2021,112653,2021
5,6,Norway,Europe,101103,2023,89154,2021,89242,2021
6,7,Switzerland,Europe,98767,2023,91992,2021,93525,2021
7,8,Singapore,Asia,91100,2023,72794,2021,66822,2021
8,9,Isle of Man,Europe,0,0,87158,2019,0,0
9,10,Cayman Islands,Americas,0,0,86569,2021,85250,2021

In [ ]:
df.tail(5)

,Unnamed: 0,Country/Territory,UN_Region,IMF_Estimate,IMF_Year,WorldBank_Estimate,WorldBank_Year,UN_Estimate,UN_Year
218,219,Malawi,Africa,496,2023,635,2021,613,2021
219,220,South Sudan,Africa,467,2023,1072,2015,400,2021
220,221,Sierra Leone,Africa,415,2023,480,2021,505,2021
221,222,Afghanistan,Asia,611,2020,369,2021,373,2021
222,223,Burundi,Africa,249,2023,222,2021,311,2021

In [ ]:
df[["Country/Territory", "UN_Region"]]

    Country/Territory UN_Region
0              Monaco    Europe
1       Liechtenstein    Europe
2          Luxembourg    Europe
3             Ireland    Europe
4             Bermuda  Americas
..                ...       ...
218            Malawi    Africa
219       South Sudan    Africa
220      Sierra Leone    Africa
221       Afghanistan      Asia
222           Burundi    Africa

[223 rows x 2 columns]